/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessage: typeof import('./src/components/chat/message/Root.vue')['default']
    ChatMessageRoot: typeof import('./src/components/chat/message/Root.vue')['default']
    ChatMessageUser: typeof import('./src/components/chat/message/user')['default']
    ChatProvider: typeof import('./src/components/chat/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.2_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a7987237dffd33053f6a8aeb6f4058ab/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.2_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a7987237dffd33053f6a8aeb6f4058ab/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.2_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a7987237dffd33053f6a8aeb6f4058ab/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
