/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatMessageAssistant: typeof import('./src/components/chat/message/assistant/index.vue')['default']
    ChatMessageAssistantDefaultMCPToolPart: typeof import('./src/components/chat/message/assistant/DefaultMCPToolPart.vue')['default']
    ChatMessageAssistantDynamicToolPart: typeof import('./src/components/chat/message/assistant/DynamicToolPart.vue')['default']
    ChatMessageAssistantElicitationRequestMCPToolPart: typeof import('./src/components/chat/message/assistant/ElicitationRequestMCPToolPart.vue')['default']
    ChatMessageRoot: typeof import('./src/components/chat/message/Root.vue')['default']
    ChatProvider: typeof import('./src/components/chat/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a4654a37f9c626ba0b04364f8150bea3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a4654a37f9c626ba0b04364f8150bea3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.28.4_@netlify+blobs@9.1.2_@upstash+redis@1.35.3_axios@1._a4654a37f9c626ba0b04364f8150bea3/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
