singleQuote: true
arrowParens: always
endOfLine: lf
printWidth: 120
jsxSingleQuote: true
vueIndentScriptAndStyle: true
semi: false
tailwindFunctions:
  - 'tv'
plugins:
  - "@prettier/plugin-oxc"
  - "prettier-plugin-tailwindcss"