packages:
  - packages/*
  - playground/*
  - apps/*

catalog:
  '@ai-sdk/openai-compatible': ^1.0.15
  '@ai-sdk/provider': 2.0.0
  '@ai-sdk/vue': 2.0.28
  '@dotenvx/dotenvx': ^1.51.0
  '@hono/node-server': ^1.19.4
  '@hono/zod-validator': ^0.7.3
  '@mastra/core': ^0.16.3
  '@modelcontextprotocol/sdk': latest
  ai: 5.0.28
  hono: ^4.9.9
  reka-ui: ^2.5.0
  zod: ^4.1.9

catalogs:
  test:
    '@testcontainers/postgresql': ^11.6.0
    '@testcontainers/valkey': ^11.6.0
    vitest: ^3.2.4

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - onnxruntime-node
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
