packages:
  - packages/*
  - playground/*
  - apps/*

catalog:
  '@ai-sdk/openai-compatible': ^1.0.15
  '@ai-sdk/provider': ^2.0.0
  '@ai-sdk/vue': 2.0.28
  '@hono/node-server': ^1.19.3
  '@hono/zod-validator': ^0.7.3
  '@mastra/core': ^0.16.3
  '@modelcontextprotocol/sdk': 1.18.1
  ai: 5.0.28
  hono: ^4.9.7
  reka-ui: ^2.5.0
  zod: ^4.1.9

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - onnxruntime-node
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
