packages:
  - packages/*
  - playground/*
  - apps/*

catalog:
  '@ai-sdk/openai-compatible': ^1.0.15
  '@ai-sdk/provider': ^2.0.0
  '@ai-sdk/vue': 2.0.28
  '@modelcontextprotocol/sdk': 1.17.4
  ai: 5.0.28
  reka-ui: ^2.5.0

catalogs:
  hono:
    hono: ^4.9.4

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - onnxruntime-node
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs

overrides:
  zod: ^3.25.0
